spring.application.name=project-vidalia-backend

## Application Properties for running tests
## DO NOT USE THIS CONFIGURATION IN PRODUCTION - it is intended for testing purposes only.
## Uses H2 in-memory database for testing, but drops and recreates the schema between test runs to ensure a clean state.
## Uses a hardcoded JWT secret for testing purposes.