spring.application.name=project-vidalia-backend

# Production Application Properties
# Includes production database configuration, JWT configuration, and logging settings
# UPDATE_THIS_BEFORE_USE - ensure to set the database connection details
