spring.application.name=project-vidalia-backend

# Production Application Properties
# Includes production database configuration, JWT configuration, and logging settings
# UPDATE_THIS_BEFORE_USE - ensure to set the database connection details

app.security.allow-h2-console=false // Disables access to H2 console in production environment
