spring.application.name=volunteering-board

# Production Application Properties
# Includes production database configuration, JWT configuration, and logging settings
# UPDATE_THIS_BEFORE_USE - ensure to set the database connection details
